### ISSUE TITLE
LatLon _Nv is not updating with lat/lon changes

### ISSUE THREAD

**Issue by jakemb21** [mrJean1/PyGeodesy#1]
First, thank you so much for converting this to python.

Been using sphericalNvector.LatLon and noticed if I update the lat/lon after I call distanceTo(), the distance is calculated using the old values (cached _Nv vector with old values) and never updates. This probably results in errors for other vector calculations as well since _Nv does not update.

Example:
`p1 = LatLon(52.205, 0.119)`
`p2 = LatLon(48.857, 2.351)`
`d1 = self.distance(p2)   # 404.3 km`
`p1.lat = 20.0`
`p1.lon = -60.0`
`d2 = self.distance(p2)   # Remains 404.3 km...should be the distance between 20.0, -60.0 and p2`

In the above example, d2 remains 404.3 km because it is still using the cached _Nv from the original p1 location.

**Comment by mrJean1** [comment]
Thank you for reporting this and I will investigate,

**Comment by mrJean1** [comment]
Actually, that is still an open design issue.  My intention was to consider the lat, lon and other  attributes read-only LatLon properties.   But the implementation does not reflect that (yet).

**Comment by mrJean1** [comment]
And then, creating a new LatLon instance should produce the correct results.

**Comment by mrJean1** [comment]
Correction ... And then, setting lat, lon and other attributes would result in an error.  Creating ...

**Comment by mrJean1** [comment]
Btw, the 2 lines above **.. = self.distance(...** should be changed to **.. = p1.distanceTo(...**.

**Comment by jakemb21** [comment]
Sorry for the typo in my example. distance() was the function (my python implementation of http://www.movable-type.co.uk/scripts/latlong.html) I was using before switching to your class.

Since I am using your class as a parent to one of my classes (airplane) I needed/wanted to be able to call airplane.lat & airplane.lon and perform any of the vector calculations with the airplane object. My airplane class has other member variables so I couldn't do a simple airplane = new LatLon(...) without losing my other data. The work around I did was modify sphericalNvector.py to have class variables _lat and _lon (similar to _Nv). I then compare them to lat and lon in toNvector(). If there is a difference between the two or _NV is None, I recalculate the n-vector. 
[sphericalNvector.txt](https://github.com/mrJean1/PyGeodesy/files/583432/sphericalNvector.txt)

I totally understand wanting to keep everything read-only. Figured I would pass this along to you in case you wanted to consider keeping your class capable of being the parent of another class. Cheers!

**Comment by mrJean1** [comment]
Thank you for presenting a use case and argument for modifying attribute values.  The class(es) should remain 'parentable', indeed and I do plan to update the code accordingly.  It may take a few weeks, though.

**Comment by mrJean1** [comment]
The code has been updated.  LatLon attributes lat, lon, height, datum, etc. are now properties.  Modifying any values resets all caches.  Let me know how this works for your application.

**Comment by mrJean1** [comment]
Closing this issue.  Please reopen if needed.

**Comment by jakemb21** [comment]
Sorry for not reporting back. Everything has been working great since the update. Been able to update the attributes in my child class and getting the results I needed. Thanks again for such great work.
