### ISSUE TITLE
No online docs.

### ISSUE THREAD

**Issue by mrJean1** [mrJean1/PyGeodesy#10]
Until further notice, the PyGeodesy docs are no longer available on PythonHosted.  The complete documentation is included in the zip distribution file at PyPI.  The wheel distribution does not include any documentation, tests and test results.

**Comment by slott56** [comment]
Can you set the repository to publish from the docs directory? It's feature of GitHub that will provide easy-to-read online docs.

**Comment by mrJean1** [comment]
Thank you!  The docs are now [here](https://mrjean1.github.io/PyGeodesy/).
