### ISSUE TITLE
wrong .sizes() output

### ISSUE THREAD

**Issue by micheda-minodes** [mrJean1/PyGeodesy#11]
first_geohash = geohash_freqs[‘geohash’].iloc[0]
sizes = pygeodesy_geohash.sizes(first_geohash)
print(first_geohash,sizes)
u336xv (4890.0, 4890.0)

for precision=6 it’s returning (   4890,    4890,     2758.887),  # 5
but it should return   (    610,    1220,      486.710),  # 6

**Comment by mrJean1** [comment]
Not sure what the problem is.  Which `geohash` function is returning the wrong values?  I am unable to reproduce the problem.  The folloowing

```
>>> from pygeodesy import geohash
>>> lat, lon = geohash.decode('u336xv')
>>> lat, lon
('52.5009', '13.354')
>>> geohash.encode(lat, lon)
'u336xv'
>>> geohash.encode(lat, lon, precision=6)
'u336xv'
>>> geohash.sizes('u336xv')
(4890.0, 4890.0)
>>> geohash.sizes('u336xv', precision=6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sizes() got an unexpected keyword argument 'precision'
```
