### ISSUE TITLE
Please add some information about how to use and test this library

### ISSUE THREAD

**Issue by E3V3A** [mrJean1/PyGeodesy#15]
Please add some information about how to:
1. install
2.  use and 
3. test this library, 

in the README file. 

Example runs showing the output would be greatly appreciated.

**Comment by mrJean1** [comment]
_PyGeodesy_ installs like most Python packages, using [pip ](https://pip.pypa.io/en/stable/installing/) or  [easy_install](https://setuptools.readthedocs.io/en/latest/easy_install.html) or [setup.py](https://stackoverflow.com/questions/1471994/what-is-setup-py) (from [setuptools](https://pythonhosted.org/an_example_pypi_project/setuptools.html)).   Following are some examples, invoked from the command line in a terminal window:

`$ pip install PyGeodesy
`

or

`$ easy_install PyGeodesy
`

or download _PyGeodesy_ from [PyPI](https://pypi.python.org/pypi/PyGeodesy/) or [GitHub](https://github.com/mrJean1/PyGeodesy), unzip the downloaded file and type:

```
$ cd PyGeodesy
$ python setup.py install
```

To run the _PyGeodesy_ tests (before installation), use

```
$ cd PyGeodesy
$ python setup.py test
```

or

```
$ cd PyGeodesy
$ python test/run.py
```

There are quite a few (albeit rather basic) examples included in the _PyGeodesy_ [documention](https://mrjean1.github.io/PyGeodesy/).  Also, there are 2,400+ tests which could be useful.  If you have a specific request for a particular use case, just ask here.

Lastly, please note, _PyGeodesy_ has only be tested on certain Python, PyPy, Intel-Python and Pythonista versions (and only on macOS or iOS).  See the [README.rst](https://github.com/mrJean1/PyGeodesy) file for further details.

HTH, _/Jean_
