### ISSUE TITLE
pip?

### ISSUE THREAD

**Issue by GliderGeek** [mrJean1/PyGeodesy#2]
Great job that you are converting the JS scripts to Python!
Are you planning to make this library accessible from pip?

**Comment by mrJean1** [comment]
Yes, but it may a while due to other commitments.

**Comment by GliderGeek** [comment]
Great!

**Comment by shahzad31** [comment]
Kindly do it as early as possible.

**Comment by mrJean1** [comment]
It will be late Feb, early Mar before the PIP is done.  There are 2 other items on the ToDo list before PIP, one of which is Epydoc (or some alternative).

**Comment by mrJean1** [comment]
First version of Epydoc-based done.

**Comment by shahzad31** [comment]
Any update on pip? perhaps i can help you in setting up pip.

**Comment by mrJean1** [comment]
Yes, see the `PyGeodesy..tar.gz` file in the` dist` directory.  Download and `untar` that file, then `cd` into the `PyGeodesy..` directory and run `python setup.py install`.  Registering at PyPI is yet TBD.

**Comment by mrJean1** [comment]
Distribution changed to a `.ZIP` file (to support Windows) and the `README` file to _reStructured text_.  The `tests` directory is a pseudo-package (using `unittest`) to allow invoking `python setup.py test` after installation with `python setup.py install`.

**Comment by mrJean1** [comment]
Waiting for feedback on `dist/PyGeodesy-*.ZIP` file before registering at and uploading to PyPI.

**Comment by psarka** [comment]
I tried `PyGeodesy-17.3.20.zip` on Ubuntu 16.04, python 2.7.12, installation worked ok, all tests passed.

**Comment by GliderGeek** [comment]
@mrJean1 : what kind of feedback would you like to receive?

**Comment by mrJean1** [comment]
Try to install the `dist/PyGeodesy-*.zip` file on your particular Python environment, like **psarka**.

**Comment by GliderGeek** [comment]
i dont see a dist folder in the repo?

**Comment by mrJean1** [comment]
Sorry, lost that directory, somehow.  Will be back soon.

**Comment by mrJean1** [comment]
The `dist` directory is back (not the _distilled_ one ;).

**Comment by GliderGeek** [comment]
I tried `PyGeodesy-17.4.4.zip` on Mac OS 12.2
- python 2.7.9: installation worked ok, all tests passed.
- python 3.6: installation work ok, all tests passed

**Comment by eilamg** [comment]
Didn't run the tests, but all three dist files (.tar.bz2, .tar.gz, .zip) for 17.4.4 installed correctly in a Python 3.5 virtualenv, Ubuntu 16.04.1.

**Comment by GliderGeek** [comment]
have to say that i was a bit confused that it have to use `import geodesy` instead of `import pygeodesy`. is there a particular reason why you use two different names?

**Comment by mrJean1** [comment]
Thank you @elamg and @GliderGeek.  No particular reason, but `PyGeodesy` contains the `geodesy` code package plus other things.

**Comment by mrJean1** [comment]
Just noticed, using `python setup.py install_lib` installs only the `geodesy` package, nothing else in the `site-packages` directory.  But `python setup.py install` installs package `geodesy` plus directories `tests` and `EGG-INFO` in directory `PyGeodesy....egg` in `site-packages`.

**Comment by GliderGeek** [comment]
wouldnt it be better if you use pygeodesy on the lower level folder as well, to avoid name collisions with the other package?

i thought it was standard to name the folder with the source the same as the package name.
the process of using the library will be very intuitive then:
`pip install pygeodesy`
in script:
`import pygeodesy`

**Comment by mrJean1** [comment]
OK, I wasn't aware of this convention and double checked, all folder and package names do match.  Therefor, the next update will change the package name from `geodesy` to `pygeodesy`.

**Comment by mrJean1** [comment]
Package name changed.  PIP is next.

**Comment by mrJean1** [comment]
[PyGeodesy](https://pypi.python.org/pypi?:action=display&name=PyGeodesy&version=17.4.8) is now on PyPI, including [documentation](http://pythonhosted.org/PyGeodesy/) on PythonHosted.

**Comment by mrJean1** [comment]
New release [PyGeodesy-17.4.9](https://pypi.python.org/pypi?:action=display&name=PyGeodesy&version=17.4.9) on PyPI.

**Comment by mrJean1** [comment]
More [PyGeodesy](https://pypi.python.org/pypi/PyGeodesy) updates at [PyPI](https://pypi.python.org/pypi/).  PyGeodesy can be installed (and uninstalled) with `pip install PyGeodesy`.
