### ISSUE TITLE
Height not interpolated in nearestOn methods

### ISSUE THREAD

**Issue by bakakaldsas** [mrJean1/PyGeodesy#25]
There is a bug in `pygeodesy.sphericalNvector` module related to heights.

`pygeodesy.sphericalNvector.LatLon.nearestOn` and `pygeodesy.sphericalNvector.LatLon.nearestOn2` do not interpolate the height on the line, only in case if endpoint is nearest the height is returned. Code to recreate:
```
>>> import pygeodesy.sphericalNvector as snv
>>> point_a = snv.LatLon(1, 1, height=100)
>>> point_b = snv.LatLon(2, 2, height=200)
>>> # Nearest is close to middle.
>>> point_c = snv.LatLon(1, 2)
>>> point_c.nearestOn(point_a, point_b)
LatLon(01°29′59.93″N, 001°29′59.31″E)
>>> point_c.nearestOn2([point_a, point_b])[0]
LatLon(01°29′59.93″N, 001°29′59.31″E)
>>> # Nearest is endpoint.
>>> point_d = snv.LatLon(0, 0)
>>> point_d.nearestOn(point_a, point_b)
LatLon(01°00′00.0″N, 001°00′00.0″E, +100.00m)
>>> point_d.nearestOn2([point_a, point_b])[0]
LatLon(01°00′00.0″N, 001°00′00.0″E, +100.00m)
```

**Comment by mrJean1** [comment]
Thank you for reporting the error.  A fix is on the way.

**Comment by mrJean1** [comment]
Take a look at the new `heights` module in `PyGeodesy 19.2.24` and the `Height...` interpolator classes, especially `HeightIDW`.

**Comment by bakakaldsas** [comment]
Thank you for the update. I checked the new versions and since it works as expected. I will close the issue.

Currently the code I am working with only uses height interpolation along the line, but the new `heights` module might come in handy in planned future development.

**Comment by mrJean1** [comment]
Make sure to use PyGeodesy 19.4.2 or later, see issue #27 Euclidean distance.
