### ISSUE TITLE
example ellipsoidalVincenty.py does not work

### ISSUE THREAD

**Issue by GliderGeek** [mrJean1/PyGeodesy#3]
the following example can be found on the top of the file:

```
Here's an example usage of Vincenty:
   
      >>> from geodesy.ellipsoidalVincenty import LatLon
      >>> Newport_RI = LatLon(41.49008, -71.312796)
      >>> Cleveland_OH = LatLon(41.499498, -81.695391)
      >>> print(Newport_RI.distance(Cleveland_OH))
      866,457.166175  # meter == 538.3904451566326 miles
```

LatLon object does not have the `distance()` function. Probably this should be `distanceTo()`

**Comment by mrJean1** [comment]
The method names in the Python version may be different from the original JS version.  If so, the original name should also exist.

**Comment by mrJean1** [comment]
There are 2 distance methods for ellipsoidal Vincenty LatLon called distanceTo and distanceTo3.  But ther is no distance method.

**Comment by mrJean1** [comment]
Also, that same test is included in the tests directory, see modules testElipsoidal.py and tests.py.

**Comment by GliderGeek** [comment]
why did you close the issue? the wrong example is still in the file.

**Comment by mrJean1** [comment]
My misunderstanding.  Module ellipsoidalVincenty has been corrected.

**Comment by mrJean1** [comment]
Thank you.
