### ISSUE TITLE
using pygeodesy in standalone application (pyinstaller)

### ISSUE THREAD

**Issue by GliderGeek** [mrJean1/PyGeodesy#31]
i am having some problems with getting pygeodesy to work when compiled using pyinstaller. it seems that the problems originate from the modifications to `sys.path` and  the checks which are taking place in `pygeodesy/__init__.py`.

# setup:
- Mac OS 10.14.4
- script.py with following content:
```python
from pygeodesy.ellipsoidalVincenty import LatLon
_ = input('Start dist calc?')
print('distance=', LatLon(50, 4).distanceTo(LatLon(51, 4)))
``` 
- using system python 3.6 (not virtualenv, as this causes problems with pyinstaller)
  - `pip3.6 install pyinstaller`
  - `pip3.6 install pygeodesy`

# Running normally
normally running the script with `python3.6 script.py` works correctly as expected.

# Compile
now compiling the script with the following command `pyinstaller script.py`.
this produces a `dist` folder in which the `script` executable can be found. running this executable leads  to the following error:

```
Traceback (most recent call last):
  File "script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "pygeodesy/__init__.py", line 245, in <module>
NameError: name 'LazyImportError' is not defined
[73850] Failed to execute script script
```

This problem originates from [this line in the init file](https://github.com/mrJean1/PyGeodesy/blob/master/pygeodesy/__init__.py#L238), which adds the pygeodesy folder to `sys.path`. This dynamic behavior is not caught by pyinstaller.
 
# Compile with added path
Explicitly adding the pygeodesy path to pyinstaller fixes the above problem:
`PYGEODESY_PATH=$(python3.6 -c "import pygeodesy; print(pygeodesy.__path__[0])")`
`pyinstaller --paths=$PYGEODEST_PATH script.py`

now running the new executable produces the following error:
```
Traceback (most recent call last):
  File "script.py", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "pygeodesy/__init__.py", line 376, in <module>
  File "pygeodesy/__init__.py", line 369, in _ismodule
ImportError: foreign module 'ellipsoidalKarney' from '/Users/matthijs/pygeodesy_bug/dist/script/ellipsoidalKarney.pyc'
```

It fails on the `_ismodule` method in the `pygeodesy/__init__.py`. Adding some prints leads to the following values for `dirname(p)` and `pygeodesy_abspath`:
- `dirname(p)`: '.../dist/script'
- `pygeodesy_abspath`:  '.../dist/script/pygeodesy'

These are indeed not equal and thus raising the exception

# Conclusion
Checking whether the imported module is indeed part of the pygeodesy distribution seems too restrictive to work with pyinstaller, which layouts the files differently. Would it be an idea to remove this restriction or add an environment flag to control this behaviour?
```python
if os.environ.get('PYGEODESY_SKIP_ISMODULE', 'false') == 'true:
    pass
else:
   # perform _ismodule(...)
```

**Comment by mrJean1** [comment]
Thank you for reporting this issue..

The restriction should be removed in __init__ somehow, as you suggested.

One thought is to check a variable like isfrozen (or something similar for PyInstaller) and if True, not add pygeodesy to sys.path.

Unfortunately, I will not be able to submit anything until the last week of June.

**Comment by GliderGeek** [comment]
Thanks for the quick reply.

I think there are two possible solutions:
- 1: only add pygeodesy to path when not frozen
- 2: never add pygeodesy to path

## 1.only add pygeodesy to path when not frozen

It seems to me that adding pygeodesy to the path bases on the `frozen` property is not a great solution. You then have to add if-statement in all places where pygeodesy modules are imported. For example: 

`__init__.py`:
```python
if frozen:
  pass
else:
   sys.path.append('pygeodesy')
```

sphericalBase.py:
```
if frozen:
   from pygeodesy.bases import LatLonHeightBase
else:
   from bases import LatLonHeightBase
```

## 2. Never add pygeodesy to path
In this case the `sys.append` command is removed and all imports on the code explicitly use the `pygeodesy` namespace. 

sphericalBase.py:
 ```
from pygeodesy.bases import LatLonHeightBase
```

I think option 2 is prefered, allthough it takes a bit more work. I am happy to provide a MR if desirable. I see it has the following advantages:
- no accidental name collisions (if user has its own `bases` module, it will never accidentally import the pygeodesy version)
- no longer problems with any sort of compiler. you do not depend on the specific `frozen` property
- no need for checking whether the modules are part of pygeodesy

**Comment by mrJean1** [comment]
One thing to try would be, (a) change line 238 in ```pygeodesy/__ini__.py``` from

```
    sys.path.insert(0, pygeodesy_abspath)
```

to

```
    if getattr(sys, ‘frozen’, False):
        # <https://pyinstaller.readthedocs.io/en/stable/runtime-information.html>
        pass  # PyInstaller bundle
    else:
        sys.path.insert(0, pygeodesy_abspath)
```

and (b) check if that avoids/solves the problem.

**Comment by GliderGeek** [comment]
i will try this and report back

**Comment by mrJean1** [comment]
Removing lines 237...238 altogether may cause problems in other cases.  As soon as I have a chance, I will try that as well.

Btw, the best option would be to use relative imports, by PyChecker can’t handle those (yet, or never).

**Comment by GliderGeek** [comment]
the suggested change did not work, because this branch is skipped (the except clause is not triggered): 
the pygeodesy folder is added to the path already and thus the import from bases succeeds.

Another fix did work: detecting pyinstaller in the `_ismodule` callable and skipping when present:
```python
def _ismodule(m):
    import sys
    if getattr(sys, 'frozen', False):
        # <https://pyinstaller.readthedocs.io/en/stable/runtime-information.html>
        return  # PyInstaller bundle
```

**Comment by mrJean1** [comment]
Good that you have a workaround for the issue.

Btw, if that except clause isn’t triggered, how could that line 238 have been a problem in the first place?  Was that a different setting/environment?

**Comment by GliderGeek** [comment]
i have created a pull request which fixes this issue.

**Comment by mrJean1** [comment]
Thank you for the pull request, I’ll incorporate that in the upcoming release.  But I’m still curious what the original error is/was you were (and no longer are) seeing.

**Comment by mrJean1** [comment]
`PyGeodesy 19.6.14` is out and includes the `PyInstaller` (and another) fix. Please close this issue if you approve.

**Comment by GliderGeek** [comment]
Unfortunately i missed some details on the latest PR. Will make another one.

**Comment by mrJean1** [comment]
Sorry, my mistake twice.  Ignore my previous comment, I did not see the 2nd pull request.

**Comment by mrJean1** [comment]
Just curious, assume function `_ismodule` looked like this:

```
        def _ismodule(m):
            p = m.__package__
            if p and p != __package__:
                raise ImportError('foreign module %r from %r' % (m.__name__, p))
```
Would that work if `_isfrozen` is `True`?

**Comment by GliderGeek** [comment]
i dont know as i dont really follow what this does? 
will try and let you know.

**Comment by mrJean1** [comment]
Since Python 3.5, the `__package__` attribute of each module is set to the name of the package, `pygeodesy` in this case.  Checking that would be better than checking the `__file__` attribute.

However, using namespace `pygeodesy` everywhere -like you suggested- is the preferred and best way.  

There are some suggestions to avoid `absolute import` and use `relative` ones, see [modulepackage](https://DaBeaz.com/modulepackage/index.html) page 37ff. and [importlib](https://docs.python.org/3/library/importlib.html).

**Comment by mrJean1** [comment]
For your review, below is an attempt to get `PyGeodesy 19.6.18` to work in a `PyInstaller 3.4` bundle using a slightly modified `script.py`.  All this is inside `venv37`, a Python 3.7.3 virtual environment on macOS 10.13.6.

```

% cat script.py
import pygeodesy
print('pygeodesy', pygeodesy.version)
from pygeodesy.ellipsoidalVincenty import LatLon
# _ = input(start dist calc?')
print('distance=', LatLon(50, 4).distanceTo(LatLon(51, 4)))


% python script.py 
pygeodesy 19.6.18
distance= 111238.68086002138


% pyinstaller -p ./lib/python3.7/site-packages/pygeodesy/ --clean script.py
66 INFO: PyInstaller: 3.4
66 INFO: Python: 3.7.3
74 INFO: Platform: Darwin-17.7.0-x86_64-i386-64bit
75 INFO: wrote ~/venv37/script.spec
79 INFO: UPX is not available.
80 INFO: Removing temporary files and cleaning cache in ~/Library/Application Support/pyinstaller
88 INFO: Extending PYTHONPATH with paths
['~/venv37',
 '~/venv37/lib/python3.7/site-packages/pygeodesy',
 '~/venv37']
89 INFO: checking Analysis
89 INFO: Building Analysis because Analysis-00.toc is non existent
89 INFO: Initializing module dependency graph...
91 INFO: Initializing module graph hooks...
92 INFO: Analyzing base_library.zip ...
4482 INFO: running Analysis Analysis-00.toc
4492 INFO: Caching module hooks...
4498 INFO: Analyzing ~/venv37/script.py
5485 INFO: Loading module hooks...
5485 INFO: Loading module hook "hook-encodings.py"...
5570 INFO: Loading module hook "hook-pydoc.py"...
5572 INFO: Loading module hook "hook-xml.py"...
5662 INFO: Looking for ctypes DLLs
5662 INFO: Analyzing run-time hooks ...
5673 INFO: Looking for dynamic libraries
5783 INFO: Looking for eggs
5783 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
5788 INFO: Warnings written to ~/venv37/build/script/warn-script.txt
5832 INFO: Graph cross-reference written to ~/venv37/build/script/xref-script.html
5845 INFO: checking PYZ
5846 INFO: Building PYZ because PYZ-00.toc is non existent
5846 INFO: Building PYZ (ZlibArchive) ~/venv37/build/script/PYZ-00.pyz
6398 INFO: Building PYZ (ZlibArchive) ~/venv37/build/script/PYZ-00.pyz completed successfully.
6408 INFO: checking PKG
6408 INFO: Building PKG because PKG-00.toc is non existent
6408 INFO: Building PKG (CArchive) PKG-00.pkg
6419 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6420 INFO: Bootloader ~/venv37/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
6420 INFO: checking EXE
6420 INFO: Building EXE because EXE-00.toc is non existent
6420 INFO: Building EXE from EXE-00.toc
6421 INFO: Appending archive to EXE ~/venv37/build/script/script
6425 INFO: Fixing EXE for code signing ~/venv37/build/script/script
6433 INFO: Building EXE from EXE-00.toc completed successfully.
6434 INFO: checking COLLECT
6435 INFO: Building COLLECT because COLLECT-00.toc is non existent
6435 INFO: Building COLLECT COLLECT-00.toc
7568 INFO: Building COLLECT COLLECT-00.toc completed successfully.


% cat script.spec 
# -*- mode: python -*-

block_cipher = None

a = Analysis(['script.py'],
             pathex=['./lib/python3.7/site-packages/pygeodesy/', '~/venv37'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='script',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='script')


% ./dist/script/script 
pygeodesy 19.6.18
distance= 111238.68086002138


% cat ./build/script/warn-script.txt 

This file lists modules PyInstaller was not able to find. This does not
necessarily mean this module is required for running you program. Python and
Python 3rd-party packages include a lot of conditional or optional module. For
example the module 'ntpath' only exists on Windows, whereas the module
'posixpath' only exists on Posix systems.

Types if import:
* top-level: imported at the top-level - look at these first
* conditional: imported within an if-statement
* delayed: imported from within a function
* optional: imported within a try-except-statement

IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
           yourself tracking down the missing module. Thanks!

excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional), ~/venv37/script.py (top-level)
missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional), ~/venv37/script.py (top-level)
missing module named _winreg - imported by platform (delayed, optional), ~/venv37/script.py (top-level)
missing module named java - imported by platform (delayed), ~/venv37/script.py (top-level)
missing module named 'java.lang' - imported by platform (delayed, optional), ~/venv37/script.py (top-level), xml.sax._exceptions (conditional)
missing module named vms_lib - imported by platform (delayed, conditional, optional), ~/venv37/script.py (top-level)
missing module named winreg - imported by platform (delayed, optional), mimetypes (optional), urllib.request (delayed, conditional, optional), ~/venv37/script.py (top-level)
missing module named org - imported by pickle (optional), ~/venv37/script.py (top-level)
missing module named nt - imported by os (conditional, optional), ntpath (conditional, optional), shutil (conditional), ~/venv37/script.py (top-level)
missing module named msvcrt - imported by subprocess (conditional), getpass (optional), ~/venv37/script.py (top-level)
missing module named _winapi - imported by encodings (delayed, conditional, optional), subprocess (conditional), ~/venv37/script.py (top-level)
missing module named 'org.python' - imported by copy (optional), ~/venv37/script.py (top-level), xml.sax (delayed, conditional)
missing module named urllib2 - imported by elevations (optional)
missing module named 'geographiclib.geomath' - imported by datum (delayed)
missing module named geographiclib - imported by datum (delayed, conditional, optional)
missing module named numpy - imported by heights (delayed)
missing module named 'scipy.interpolate' - imported by heights (delayed)
missing module named scipy - imported by heights (delayed)
missing module named StringIO - imported by geoids (optional)
```

**Comment by GliderGeek** [comment]
Yes, i also got it to work with 19.6.18 :+1:

**Comment by mrJean1** [comment]
Good to hear/see that.  No need to check the __package__ attribute.

**Comment by mrJean1** [comment]
The very latest `PyGeodesy 19.06.26` includes a simpler` __init__.py` file (plus 5 new modules `etm` and `elliptic` for _Exact Transverse Mercator_ projection and 3 mostly internal ones `deprecated`, `named` and `utmupsBase`).

**Comment by GliderGeek** [comment]
Did you ever consider adding a changelog? I allways find it very handy:
https://keepachangelog.com/en/1.0.0/

**Comment by mrJean1** [comment]
No, but I’ll look into it.  Thank you!

**Comment by GliderGeek** [comment]
i think this one can be closed
