### ISSUE TITLE
Can i use this library on with asyncio

### ISSUE THREAD

**Issue by britisharmy** [mrJean1/PyGeodesy#37]
Does this library support async methods with asyncio?

**Comment by mrJean1** [comment]
PyGeodesy has no dependency on and no known conflict with `asyncio`.  

PyGeodesy should work properly in multi-threaded applications, except for a few functions with global state: `crosserrors`, `limiterrors`, `precision` and 'rangeerrors'.  However, PyGeodesy has not been testing specifically under such conditions.

PyGeodesy modules `elevations`, `geoids` and `heights` do I/O, for example to load geoid grid files.  Modules `css`, `datum`, `ellipsoidalKarney`, `geoids`, `hausdorff` and `heights` _may_ need external packages `geographiclib`, `numpy` and/or `scipy`, see the PyGeodesy documentation for details.

**Comment by britisharmy** [comment]
Many thanks for the lengthy answer.  I was thinking that all geodesy functions are async.

**Comment by mrJean1** [comment]
One way to harden PyGeodesy instance in a multi-threading application would be the following (untested).

```
from pygeodesy.ellipsoidalVincenty import LatLon
from threading import RLock

class SafeLatLon(LatLon):
    _rLock = None
    ...

    def __init__(self, *args, **kwds):
        self._rLock = RLock()
        LatLon.__init__(self, *args, **kwds)

    @property
    def P(self):
        with self._rLock:
             return LatLon.P(self)

    @P.setter
    def P(self, value):
        with self._rLock:
            LatLon.P(self) = value

    def M(self, *args):
        with self._rLock:
            return LatLon.M(self, *args)

    ...
```
That pattern must be repeated for each property `P` and each method `M` in every PyGeodesy class used in the multi-threaded application.  Obviously, this is rather tedious for general usage.

Better would be if PyGeodesy (could) make all class properties and methods thread-safe, for example with a `@safePoperty` and `@safeMethod` decorator.  Also, untested.

**Comment by britisharmy** [comment]
I shall definitely try this out and see its merits. 

Thanks for taking time to look at this, i appreciated.
