### ISSUE TITLE
Conversion from LatLon to OSGR and back may cause systematic offset

### ISSUE THREAD

**Issue by jaluebbe** [mrJean1/PyGeodesy#38]
Conversion between Lat/Lon and OSGR is not always reversible. See the following examples:
osgr = toOsgr(eV.LatLon(52, -0.12))
osgr.toStr2()
'[G:TQ, E:32014, N:23971]'
ll = osgr.toLatLon(eV.LatLon); (ll.lat, ll.lon)
(51.0, -0.12) # consistent to input
(osgr.easting, osgr.northing)
(532014.2352530259, 123971.60890206805)
Osgr(osgr.easting, osgr.northing)
[G:TQ, E:32014, N:23971]
o = Osgr(532014, 123971).toLatLon(eV.LatLon); (o.lat, o.lon)
(50.99918767451807, -0.12151217235660071) # not consistent to input
https://www.movable-type.co.uk/scripts/latlong-os-gridref.html provides 
(50.999995, 0.120004) for 'TQ 32014 23971'.
toOsgr(eV.LatLon(o.lat, o.lon))
[G:TQ, E:31910, N:23878] # consistent to result from https://www.movable-type.co.uk/scripts/latlong-os-gridref.html for (50.99918767451807, -0.12151217235660071)

**Comment by mrJean1** [comment]
Thank you for reporting.  The discrepancy may be due to a datum conversion issue.  Will be investigate further and get back shortly.

**Comment by jaluebbe** [comment]
This issue appears for osgr.copy().toLatLon(eV.LatLon) too which differs significantly to osgr.toLatLon(eV.LatLon). But osgr.copy().copy().toLatLon(eV.LatLon) doesn't introduce any additional offset.

**Comment by mrJean1** [comment]
Again, thank you!  Found and fixed one issue, in `Osgr.copy`, still investigating another and adding test cases to `testOsgr.py`.

**Comment by mrJean1** [comment]
Finally resolved the other issue, in `CartesianBase.convertDatum`.  New release forthcoming, soon.

**Comment by jaluebbe** [comment]
Thanks, it seems to work properly now.

**Comment by jaluebbe** [comment]
This inconsistency occurs especially close to the edge of the OS grid: 
# location on the Isles of Scilly
lat = 49.926244
lon = -6.297934
latlon = eV.LatLon(lat, lon)
osgr = toOsgr(latlon)
osgr_new = Osgr(osgr.easting, osgr.northing)
latlon_osgr_new = osgr_new.toLatLon(eV.LatLon)
print('latlon_osgr_new', latlon_osgr_new)
latlon_osgr_new 49.926244°N, 006.298699°W, +50.99m # What does this +50.99m mean? The new location has a distance of ~55m to the original lat, lon.

**Comment by mrJean1** [comment]
Thank you for reporting.  The +50.99m figure represents the elevation of height above the ellipsoid.

I will double check the discrepancy, especially with the original [here](https://www.movable-type.co.uk/scripts/latlong-os-gridref.html).

**Comment by mrJean1** [comment]
Here is the result with [PyGeodesy 20.7.12](https://github.com/mrJean1/PyGeodesy) for the same test above ...

```
>>> osgr2 = pygeodesy.Osgr(osgr.easting, osgr.northing)
>>> ll4 = osgr2.toLatLon(LatLon=LL)
>>> ll4
LatLon(49°55′34.48″N, 006°17′52.56″W, +50.99m)
>>> ll1.distanceTo(ll4)
0.0014737726553611847
```

Please verify and close the issue if confirmed.  Again, thank you for reporting and offering a test case.

**Comment by jaluebbe** [comment]
Thanks, it passed my tests as well. It will be available with pip in the future?

**Comment by mrJean1** [comment]
It is on PyPI <https://pypi.org/project/PyGeodesy/> too.

/Jean
