### ISSUE TITLE
Trilaterate by area

### ISSUE THREAD

**Issue by AleixDev** [mrJean1/PyGeodesy#43]
Is there any way to trilaterate when some of the circles are not intersecting with the perimeter but with the area?

For example, I would like to trilaterate this circles, but it only works when they are intersecting with the perimeter:
```
from pygeodesy.sphericalNvector import LatLon

distance = 5110

p1 = LatLon(42.688839, 2.438857)
p2 = LatLon(42.635421, 2.522570)
p3 = LatLon(42.64540, 2.504811)
t = p1.trilaterate(distance, p2, distance, p3, distance)
print('trilaterate:', t.lat, t.lon) # (INCORRECT: 43.051858748236725, 2.944630261790253)


p1 = LatLon(42.688839,2.438857)
p2 = LatLon(42.635421,2.522570)
p3 = LatLon(42.630788,2.500713)
t = p1.trilaterate(distance, p2, distance, p3, distance)
print('trilaterate:', t.lat, t.lon) # (CORRECT: 42.67456065072384, 2.4953950233084456)
```

Incorrect:
![Incorrect](https://user-images.githubusercontent.com/6617055/93439562-00967300-f8cf-11ea-965e-8aa0d79f4a15.png)
Correct:
![Correct](https://user-images.githubusercontent.com/6617055/93439541-faa09200-f8ce-11ea-904c-55c92243ed71.png)

**Comment by mrJean1** [comment]
Thank you for posting the issue.  The images are very helpful.  Two things.

1. At least the first example must be a bug in `sphericalNvector.trilaterate`.  The distance from trilaterated point `t` to all three points `p1`, `p2` and `p3` is the same, but very different from the given `distance` value.  After adding the following 3 lines to both examples:

```
print('trilaterate:', t.lat, t.lon)
...
print(t.distanceTo(p1))
print(t.distanceTo(p2))
print(t.distanceTo(p3))
```
the results are

```
trilaterate: 43.05185874823812 2.9446302617919247
57691.28241925844
57691.28241925878
57691.282419259085

trilaterate: 42.67456065072385 2.4953950233084585
4886.695113883056
4886.695113882949
4886.695113883015
```

As expected, the 3 distances in each example are the same.  However, in the first example, 57691 is much larger than the given distance 5110.  That is one issue to be investigated further.

In the second example, the value of 4886 is close to and less than 5110.  The difference is about 4% which seems a bit large, but may be within the accuracy of the `-Nvector` code.  Another issue to be investigated further.


2. Does _trilaterate by area_ mean determine whether the 3 circles overlap, i.e. have some area in common, like a the [Intersection](https://wikipedia.org/wiki/Intersection_(set_theory)) part of a [Venn](https://wikipedia.org/wiki/Venn_diagram) diagram?  If so, _perhaps_ the following method _may_ work ... "for each pair of circles, determine the intersection point or points.  The determine whether the line (segment) between the intersection points (aka the [radical](https://mathworld.wolfram.com/Circle-CircleIntersection.html) line) overlaps the third circle" ... _Untested_ and also to be investigated further.

In any case, the most recent `Pygeodesy` releases include a function and `LatLon` method called `intersections2` to compute the intersection point(s) of 2 circles in the `sphericalTrigonometry`, `ellipsoidalVincenty` and `ellipsoidalKarney` (but not in the `-Nvector)` modules.  Perhaps, those could be used to build _trilaterate by area_.

**Comment by AleixDev** [comment]
1. Okay I see... In my case, the second example is nearly correct so it's not a big issue for me. The first one is what worries me.
2. Yes, sorry that was what I meant (I didn't know exactly how to say that).

Thank you very much for your response! I will try your suggestions and I'll let you know if I achieve something relevant.

**Comment by mrJean1** [comment]
For your consideration, following an initial attempt for a function `triliterateBy2` to provide _trilaterate-by-area_ or _-by-perimeter_. 

For all 3 circle combinations, it uses the `LatLon.intersections2` method to get the intersection points between the 1st and 2nd circle.  

For the _-by-area_ case, it then uses the `nearestOn` method to get the nearest point between in the _radical segment_ and the center of the 3rd circle.  If the distance between those is less than the radius of the 3rd circle (less the given margin `eps`), there is overlap.

For the _-by-perimeter_ case, it computes the distance between the center of the 3rd circle and the intersection points of the 1st and 2nd circle.  Then, it compares the required margin with the closest distance to the closest intersection point.

```
from pygeodesy import EPS, IntersectionError
from pygeodesy.sphericalTrigonometry import LatLon

distance = 5110

if True:
    p1 = LatLon(42.688839, 2.438857)
    p2 = LatLon(42.635421, 2.522570)
    p3 = LatLon(42.64540, 2.504811)
else:
    p1 = LatLon(42.688839,2.438857)
    p2 = LatLon(42.635421,2.522570)
    p3 = LatLon(42.630788,2.500713)


def trilaterateBy2(p1, d1, p2, d2, p3, d3, area=True, eps=EPS, radius=R_M):
    '''Trilaterate 3 points by area (overlap) or perimeter (intersection).
 
       Margin C{eps} is the required I{minimal overlap} for C{area=True}
       or the I{maximally allowed intersection error} for C{area=False}
       in the same units as C{radius} passed to method C{.distanceTo}.

       @return: 2-Tuple(distance, point) with the C{distance} and
                intersection C{point}.  If there is no area overlap
                or perimeter intersection the returned result is
                C({None, None)}.
   '''
    for _ in range(3):
        p1, d1, p2, d2, p3, d3 = p2, d2, p3, d3, p1, d1
        try:
            c1, c2 = p1.intersections2(d1, p2, d2)
            if area:  # check overlap
                if c1 is c2:  # abutting
                    c = c1
                else:  # nearest point on radical
                    c = p3.nearestOn(c1, c2, radius=R_M)
                d = d3 - p3.distanceTo(c)
                if d > eps:  # min overlap required
                    return d, c

            else:  # check intersection
                for c in ((c1,) if c1 is c2 else (c1, c2)):
                    d = abs(d3 - p3.distanceTo(c, radius=R_M))
                    if d < eps:  # max distance allowed
                        return d, c

        except IntersectionError:
            # no intersection, concentric, etc.
            if area:
                pass
            else:
                break

    return None, None

for area in (False, True):
    d, t = trilaterateBy2(p1, distance, p2, distance, p3, distance, area=area, eps=10)  # meter
    print('trilaterateBy', area, d, (t.lat, t.lon) if t else t)
```

One note, `triliterateBy2` only works with `sphericalTrigonometry.LatLon` due to the lack of the `nearestOn2` method for `ellipsoidal LatLon` classes.

**Comment by mrJean1** [comment]
On issue 1, the result of your first example.  Strictly speaking, the result may be a valid _trilaterate_ intersection based on `-Nvector` math but that is unexpected.  Would it be helpful if there was a keyword argument to specify whether the intersection point must be on or near the perimeter?

**Comment by mrJean1** [comment]
Another comment on the `trilaterateBy2` function.   That does not handle pathological cases like concentric circles, yet.  It is still a question, what is the correct result for 3 concentric circles?

**Comment by AleixDev** [comment]
Thank you, that's exactly what I needed!! It works in all the cases that I have tested so far :))


> On issue 1, the result of your first example. Strictly speaking, the result may be a valid trilaterate intersection based on -Nvector math but that is unexpected. Would it be helpful if there was a keyword argument to specify whether the intersection point must be on or near the perimeter?

Do you mean the result of the second example (`42.67456065072384, 2.4953950233084456`)..? :thinking: Anyways I think that adding this argument could be a nice addition (although not mandatory for me).


> Another comment on the trilaterateBy2 function. That does not handle pathological cases like concentric circles, yet. It is still a question, what is the correct result for 3 concentric circles?

I think that the correct result would be to return the center of the circles. Just like what happens with your code, when you use nearly concentric circles like this:
```
distance = 5110
p1 = LatLon(42.688839,5.438857)
p2 = LatLon(42.688839,5.438857)
p3 = LatLon(42.688839,5.438858)
d, t = trilaterateBy2(p1, distance, p2, distance, p3, distance, area=True, eps=10)
print(t) # (returns: [42.688839, 5.438857674568252])
```
![image](https://user-images.githubusercontent.com/6617055/93623371-ed72c880-f9de-11ea-8203-7408d41c6a81.png)

**Comment by mrJean1** [comment]
Thank you for your comments!  I plan to add a method/function `trilateralBy` based on your suggestions.

One more case: two circles _do not overlap and do not intersect_ but both _are inside and covered_ by the third circle?

**Comment by AleixDev** [comment]
I've tested it and seems to work perfectly with every situation so far. Thanks again!

**Comment by mrJean1** [comment]
The latest [PyGeodesy 20.9.23](https://github.com/mrJean1/PyGeodesy) release includes a new method `trilaterate5` for all `ellipsoidalKarney.-`, `ellipsoidalVincenty.-` and `sphericalTrigonometry.LatLon` classes to trilaterate 3 circles by intersection of overlap (and with some restrictions for `ellipsoidal-` and `sphericalNvector.LatLon`).

The trailing `-5` in the name `trilaterate5` reflects the returned result, a 5-tuple returned as result.  More details in the [documentation](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.ellipsoidalBase.LatLonEllipsoidalBase-class.html#trilaterate5).

Separately, the original `sphericalNvector.LatLon.trilaterate` method and `sphericalNvector.trilaterate` function has been fixed to no longer report false trilaterations (without using an `eps`-like tolerance).  And that `.trilaterate` method is now also available for the `ellipsoidalNvector.LatLon` class.

Lastly, several new `trilaterate` tests are based on your examples.  Thank you again for reporting the original problem.

**Comment by mrJean1** [comment]
[PyGeodesy 20.9.29](https://pypi.org/project/PyGeodesy/) includes yet another trilateration function [`trilaterate3d2`](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.vector3d-module.html#trilaterate3d2).  That compute the intersections of 3 spheres using [this novel, algebraic](https://www.researchgate.net/publication/275027725_An_Algebraic_Solution_to_the_Multilateration_Problem) method (and `numpy`).

Interestingly, `trilaterate3d2` with the earth as one of the spheres centered at (0, 0, 0) produces the same intersections as the [spherical Cartesian.intersections2](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.sphericalBase.CartesianSphericalBase-class.html#intersections2) method.

Closing this issue.
