### ISSUE TITLE
Is it possible to calculate elevation above sea level?

### ISSUE THREAD

**Issue by CalebBell** [mrJean1/PyGeodesy#44]
Hi mrJean1!
I am trying to retrieve the elevation of many <lat, lon> pairs. I had no problem using PyGeodesy to do the EGM2008 lookups as your great documentation describes. For example Calgary, AB is at an elevation of ~1045 m. The lookup gives a different result.

```
>>> from pygeodesy import *
>>> predictor = GeoidPGM("/home/caleb/Desktop/egm2008-5.pgm")
>>> pt = points.LatLon_(51.05011, -114.08529)
>>> predictor(pt)
-16.804670290052883
```

I realize the lookup isn't returning elevation above sea level but rather the height of the geoid above the WGS84 ellipsoid. I also realize the values returned are consistent with [other tools](https://geographiclib.sourceforge.io/cgi-bin/GeoidEval?input=51.05011+-114.08529&option=Submit). 

I was wondering if there was a way to use PyGeodesy to convert that result into elevation above sea level? I apologize if this is out of scope or a dumb question; geoinformatics is not my field by trade.

Sincerely,
Caleb

**Comment by mrJean1** [comment]
Try the fuunction [elevations2](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.elevations-module.html#elevation2).

**Comment by CalebBell** [comment]
Thank you very much for the pointer!

**Comment by mrJean1** [comment]
Sorry, 2 mistakes.  (1) The function name is `elevation2`.  (2) The [NED.USGS service](https://NED.USGS.gov/epqs/pqs.php) is limited to the _conterminous US_.

**Comment by abubelinha** [comment]
@mrJean1 the last link is dead.  
Anyway, do you mean the function only works for US territory? (not for World lat-lon points)

**Comment by mrJean1** [comment]
1) Thank you for reporting the broken link.

2) Both functions `elevation2` and `geoidHeight2` are limited to the _conterminous US_, see the documentation of the _elevations_ module.

3) See also the documentation of the _geoid_ module, especially [this link](https://wiki.ros.org/mavros#mavros.2FPlugins.Avoiding_Pitfalls_Related_to_Ellipsoid_Height_and_Height_Above_Mean_Sea_Level).
