### ISSUE TITLE
GeoidKarney leaves resources open

### ISSUE THREAD

**Issue by DanMcGann** [mrJean1/PyGeodesy#50]
The GeoidKarney class fails to close the underlying EGM file when the class goes out of scope.

Below is a minimal example to describe the problem.

```
from pygeodesy.geoids import GeoidKarney
import unittest

class TestGeoidDestructor(unittest.TestCase):
    def test_karney(self):
        geoid = GeoidKarney("/usr/local/share/GeographicLib/geoids/egm96-5.pgm")

if __name__ == "__main__":
    unittest.main()
```
Which generates the following output and warning...
```
/usr/lib/python3.8/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/local/share/GeographicLib/geoids/egm96-5.pgm'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 1 test in 0.003s
OK
```

A quick look through the source code also showed that there was nowhere that the `self._egm` was being closed.

Automatic closure of the resource or the addition of an explicit `close` method to the geoid interface would be a great addition to the project.

---

Technical Details
Python 3.8.5
pygeodesy 21.03.03

**Comment by mrJean1** [comment]
`GeoidKarney` needs the file to stay open to get to the geoid heights.  Pehaps, it should behave like a file and/or offer context methods.  To be investigated, soon.

**Comment by mrJean1** [comment]
Forthcoming version 21.04.04 of PyGeodesy includes 2 new methods `close` and `closed` for the `GeoidKarney` class plus the `__enter__` and `__exit__` methods to allow the class to be used in a `with GeoidKarney(...) as ...` context.  This applies to all `Geoid...` classes but is only effective for `GeoidKarney` since only the latter must keep the `egm*.pgm` file open.

The unit test case will continue to fail unless modified to ...
```
class TestGeoidDestructor(unittest.TestCase):
    def test_karney(self):
        geoid = GeoidKarney("/usr/local/share/GeographicLib/geoids/egm96-5.pgm")
        geoid.close()
```
... or, preferably ...
```
class TestGeoidDestructor(unittest.TestCase):
    def test_karney(self):
        with GeoidKarney("/usr/local/share/GeographicLib/geoids/egm96-5.pgm") as geoid:
            pass
```

**Comment by mrJean1** [comment]
PyGeodesy 21.04.04 is on [GitHub](https://github.com/mrJean1/PyGeodesy) and [PyPi](https://pypi.org/project/PyGeodesy/) (with 2 minor test failures for `trilaterate3d2`).  Please review and close this issue.
