### ISSUE TITLE
Why intern floats?

### ISSUE THREAD

**Issue by mapadofu** [mrJean1/PyGeodesy#52]
I hope it's okay to just ask a question and not a bug.

I was reading through the code and I noticed the logic in the `interns` module relating to maintaining a dict of the floating point constants defined in it.  Why is this being done?   

I see how `len(inters._floats)` is used in reporting out the number of constants defined when you `python -m pygeodesy`, is that the only purpose for maintaining this dict, or is it doing some kind of useful interning of the constants?

**Comment by mrJean1** [comment]
Indeed.  There are several (large) tables of the same `float` coefficients and the same `float` constants in `pygeodesy` modules.  Having the `float` value `intern`ed across modules helps save (some) space and (some) lookup time.

In previous versions of Python, only `str`'s and small `int`s were `intern`'ed for that reason.  Although function `intern` has been deprecated, recently, the notion of `itern`ing is still worth preserving.

Similarly but separately, `lazy import`, `cached` or `memoized` properties are optimizations worthwhile.  Those were tricky to accomplish previously, but recent Python 3+ versions offer more support.

HTH
