### ISSUE TITLE
trying to get coordinates in the center of a mgrs cell

### ISSUE THREAD

**Issue by abubelinha** [mrJean1/PyGeodesy#54]
Thanks for this great library, and sorry for the doom question.

This is what I am doing to convert mgrs reference to both utm and lat/lon coordinates.

```
mgrs_string = "31TDF3182"
from pygeodesy import mgrs
utm = mgrs.parseMGRS(mgrs_string).toUtm()
print(utm)
latlon = utm.toLatLon()
print(latlon)
```

output:

```
31 N 431000 4582000
(41.38657, 2.174726, Datum(name='WGS84', ellipsoid=Ellipsoids.WGS84, transform=Transforms.WGS84), -0.54564, 0.999659)
```

This works fine, but I am getting the coordinates of the bottom left corner of my mgrs cell.
I want to get the cell's center point.
As in this case the cell size is 1 square Km, it would be just a matter of adding 500 to each utm coordinate, but I don't know what is the best/quickest approach to do it.
So I have some questions related to this:

- Is there any built in parameter to ask mgrs.toUtm() to return the center of mgrs cell?
- Perhaps a built in method to sum a certain number of meters to x and/or y coordinates of the utm object?
- Or at least, could I get Northing and Easting from utm object in a direct way? latlon.lat gives me latitude, but I couldn't get any values from utm.E , utm.Easting , utm['E'] ...

I have not great python skills: what I am doing for now is parsing utm.toStr(), and then splitting the string to get utm Northing and Easting in meters. Then, calculating how big the cell is I know how many meters I should add to N & E ... which looks a bit too much work to me.

Thanks again !!

**Comment by mrJean1** [comment]
Here is a function to get the lat- and longitude of the center location.

```
from pygeodesy import mgrs, Utm

def mgrs2latlon(mgrstr):
    r = mgrs.parseMGRS(mgrstr).toUtm()
    # get half the precision in meter
    i, h = len(mgrstr), 50000  # 50 Km
    while i and mgrstr[i-1].isdigit():
        i -= 2
        h  = h // 10
    u = Utm(r.zone, r.hemisphere,
            r.easting + h, r.northing + h,
            band=r.band, datum=r.datum, name=r.name)
    return u.toLatLon()

print(mgrs2latlon('31TDF3182'))

(41.391116, 2.180649, Datum(name='WGS84', ellipsoid=Ellipsoids.WGS84, transform=Transforms.WGS84), -0.541772, 0.999658)
```

Better might for the `parseMGRS` function and `Mgrs` class to remember the precision.  That may be an enhancement.

**Comment by mrJean1** [comment]
[PyGeodesy version 21.6.16](https://github.com/mrJean1/PyGeodesy/) includes a new method `toLatLon`, a new property `resolution` and a new keyword argument for methods `__init__` and `toUtm` in class `Mgrs`.  Thank you for posting the issue and the example.

**Comment by abubelinha** [comment]
Thank you so much @mrJean1
Just want to ask, what about this optional `center` argument when we want to do the opposite thing? Going from utm (or latlon) to MGRS ... shouldn't we somehow tell PyGeodesy if the original point will be the center or the corner of the returned MGRS cell?

Not sure if this is the best place to ask it, but I feel the following questions are quite related to this so I prefer not to bother you opening a new issue.
In my example above, I didn't state Datum WGS84, so I suppose it was asummed by default.

So, what if I want to **transform coordinates between different coordinate systems/datums**?

I mean something similar to what this library does:
https://github.com/proj4js/proj4js

Is PyGeodesy able to do it, could you link me to an example of this kind of transformations?
A couple of examples of what I would like to do:

(1) Source: MGRS (100 m precision) 31TDF314824, datum ED50, http://epsg.io/23031
Some possible intended targets: 
- UTM (mgrs cell center), datum ED50, http://epsg.io/23030
- UTM (mgrs cell center), datum ETRS89, http://epsg.io/25831
- UTM (mgrs cell lowerleft corner), datum ETRS89, http://epsg.io/25830
- LatLon (mgrs cell lowerleft corner), datum WGS84, http://epsg.io/4326

(2) Source: LatLon 37.2075843, -6.9261187, WGS84, http://epsg.io/4326
Some possible intended targets: 
- UTM, datum ETRS89, http://epsg.io/25829
- MGRS 10m precision (lowerleft anchor), datum ETRS89, http://epsg.io/25829
- MGRS 100m precision (center anchor), datum ED50, http://epsg.io/23029
- UTM, datum ED50, http://epsg.io/23030

And another related question: 
I am completely ignorant about all the maths behind this, but I have also read that for some regions the accuracy of transformation calculations is not that good. 
So in those cases **[transformation grids](https://proj.org/usage/transformation.html?highlight=nadgrids#grid-based-datum-adjustments)** (and related [grid files](https://proj.org/resource_files.html#transformation-grids)) come to the rescue. 
I wonder if PyGeodesy can also handle these high-accuracy transformations (for the examples I provide, this [Iberian Peninsula grid file](http://www.ign.es/web/resources/docs/IGNCnig/GDS-TOOLS-PENR2009.zip) linked in this [proj4js issue](https://github.com/proj4js/proj4js/issues/62#issuecomment-25019400) is the appropriate one). 

Please tell me if you prefer me to open a new issue to post all this stuff.
And thanks a lot for your invaluable help.

**Comment by mrJean1** [comment]
On going from `LatLon` and/or `Utm` to `Mgrs`, there are some functions and methods named `toMgrs`.  Those should have a keyword argument `center`, indeed.  However, it's unclear how that should work since the resolution/cellsize has to be discovered somehow.  Looking into that.

Regarding transforming between datums, see if the `toDatum` method of the [LatLon](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy-LatLon-attributes-table.html) and [Cartesian](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy-Cartesian-attributes-table.html) classes does that.  More later.

**Comment by abubelinha** [comment]
Thanks for your answer.
This is going beyond my understanding of concepts, but I'll try to see all what you suggest.

At a first try, I couldn't make toDatum(). What am I doing wrong here?

```
# I actually want to go from MGRS https://epsg.io/23031 to LatLon https://epsg.io/25831

# is Datums.ED50 enough or do I need something else to make PyGeodesy read EPSG:23031 ??
m = mgrs.parseMGRS("31TDF3182", datum=Datums.ED50)

u = m.toUtm()
ll1 = u.toLatLon()
ll2 = ll1.toDatum(datum2=Datums.WGS84)
```
The last line raisses an error:
`AttributeError: 'LatLonDatum5Tuple' object has no attribute 'toDatum'`


BTW, I am not sure if Datums.ED50 is correct above, or I should provide something else if my original coordinates are in EPSG:23031

**Comment by mrJean1** [comment]
All good, except missing is specifying the LatLon class to use.  Here is the complete example:
```
from pygeodesy import Datums, ellipsoidalVincenty as eV, mgrs

m = mgrs.parseMGRS("31TDF3182", datum=Datums.ED50)

u = m.toUtm()  # don't bother with center/lowerleft corner for now

ll1 = u.toLatLon(LatLon=eV.LatLon)  # or ellipsoidalExact.LatLon, etc.
print(ll1)

ll2 = ll1.toDatum(datum2=Datums.WGS84)
print(ll2)

ll2.height= 0
print(ll2)
```
Datum conversion requires a cartesian, Helmert transformation and often results in a different, non-zero height.

**Comment by mrJean1** [comment]
One question still remains.  The example above is about changing the datum or ellipsoid.  Changing reference frame is different and perhaps that is what your usecase needs.  The Python code is similar, an example using a different LatLon class as well.
```
from pygeodesy import Datums, ellipsoidalExact as eX, mgrs, RefFrames  # 2 changes

m = mgrs.parseMGRS("31TDF3182", datum=Datums.ED50)

u = m.toUtm()

ll1 = u.toLatLon(LatLon=eX.LatLon, reframe=RefFrames.ITRF2000)  # 2 changes
print(ll1)
41.385846°N, 002.174773°E

ll2 = ll1.toRefFrame(RefFrames.GDA2020)  # 2 changes
print(ll2)
41.385854°N, 002.174774°E, -0.03m

ll2.height= 0
print(ll2)
41.385854°N, 002.174774°E

print(RefFrames.ITRF2000)  # change
name='ITRF2000', epoch=1997, ellipsoid=Ellipsoid(name='GRS80')

print(RefFrames.GDA2020)  # change
name='GDA2020', epoch=2020, ellipsoid=Ellipsoid(name='GRS80')
```

**Comment by mrJean1** [comment]
One more thing.  Use the new `Mgrs.toLatLon` method with PyGeodesy 21.6.16 or newer, examples.
```
from pygeodesy import Datums, ellipsoidalVincenty as eV, ellipsoidalExact as eX, mgrs, RefFrames

m = mgrs.parseMGRS("31TDF3182", datum=Datums.ED50)

ll1 = m.toLatLon(LatLon=eV.LatLon)
print(ll1)

ll1 = m.toLatLon(LatLon=eX.LatLon, reframe=RefFrames.ITRF2000)
print(ll1)
```

**Comment by mrJean1** [comment]
Wrt to converting a centered `LatLon` back to `Mgrs` (via `Utm`).

The current `PyGeodesy` code produces the following:
```
from pygeodesy import Datums, ellipsoidalVincenty as eV, mgrs, RefFrames, F_D

m = mgrs.parseMGRS("31TDF3182", datum=Datums.ED50)

ll = m.toLatLon(LatLon=eV.LatLon)  # center=True
print(ll, '=', ll.toUtm().toMgrs())
# 41.391116°N, 002.180649°E = 31T DF 31500 82499

ll = m.toLatLon(LatLon=eV.LatLon, center=False)
print(ll, '=', ll.toUtm().toMgrs())
# 41.38657°N, 002.174726°E = 31T DF 31000 82000
```

There is currently no (ellipsoidal) `LatLon.toMgrs` method, but one is being added with a keyword argument `center=False` (unlike `LatLon.toMgrs`).  If `center=False`, the resulting `Mgrs` location will be returned as-is.

However, _if_ `center=True` _and if_ the last nonzero digit of easting and northing is 5 (and near 5), the easting and northing values will be truncated down.  It will take some testing to make sure corner cases are covered.

**Comment by abubelinha** [comment]
Thanks a lot @mrJean1 for this last example.
The previous ones are also very welcome, but unfortunately they are too technical for me.

I was hoping something more easy and direct, like the way of transforming coordinates just calling crs names, like in this [pyproj example](https://pyproj4.github.io/pyproj/stable/examples.html#step-2-create-transformer-to-convert-from-crs-to-crs).
```
from pyproj import Transformer
transformer = Transformer.from_crs("EPSG:4326", "EPSG:26917")
transformer.transform(50, -80)
```
That's really simple ... but I found not way of handling mgrs. 
That's why I googled and found PyGeodesy.

**Comment by mrJean1** [comment]
Well, it's be straightforward to the same in PyGeodesy, if `EPSG:4326 == WGS84`, `EPSG:26917 == NAD83` and assuming the `transformer.transform` takes a `lat` and `lon`.
```
from pygeodesy import Datums, ellipsoidalVincenty

class Transformer(object):
    def __init__(self, datum1, datum2):
        self._datum1 = datum1
        self._datum2 = datum2

    def transform(self, lat, lon):
        ll = ellipsoidalVincenty.LatLon(lat, lon, datum=self._datum1)
        return ll.toDatum(self._datum2).latlon

transformer = Transformer(Datums.WGS84, Datums.NAD83)
ll = transformer.transform(50, -80)

print(ll)
# (49.999976, -79.999989)
```
If you need something similar but for MGRS locations, show an example you prefer, like the one above.

**Comment by mrJean1** [comment]
In any case, thank you for the questions and examples.  All those did help to improve PyGeodesy.

Please close this issue if no longer needed.
