### ISSUE TITLE
Typo in pygeodesy/sphericalTrigonometry.py

### ISSUE THREAD

**Issue by doinab** [mrJean1/PyGeodesy#55]
(With thanks for the work:)

"heighth" on line 985 makes intersection() crash with:

     __init__() got an unexpected keyword argument 'heighth'

**Comment by mrJean1** [comment]
Thank you for reporting!  `PyGeodesy 21.6.26` is  forthcoming.

**Comment by mrJean1** [comment]
Please, see [PyGeodesy 21.6.26](https://pypi.org/project/PyGeodesy/).
