### ISSUE TITLE
`initialBearingTo` returns wrong values for points on same meridian

### ISSUE THREAD

**Issue by bakakaldsas** [mrJean1/PyGeodesy#56]
I didn't go into too much research reproducing this, but it seems that the method `pygeodesy.sphericalNvector.LatLon.initialBearingTo` always returns 0.0 if both points are on the same meridian. It should return 180.0 if the `point_from` is to the north from the `point_to`. Results seem to be correct as long as points are shifted at least a bit on the Lon axis.

Code snippet to reproduce the issue:
```
>>> import pygeodesy
>>> pygeodesy.__version__
'21.06.29'
>>> from pygeodesy.sphericalNvector import LatLon
>>> point_a = LatLon(5, 5)
>>> point_b = LatLon(10, 5)
>>> point_a.initialBearingTo(point_b)
0.0
>>> point_b.initialBearingTo(point_a)
0.0
>>> point_c = LatLon(10, 5.0000001)
>>> point_a.initialBearingTo(point_c)
1.1299401739210769e-06
>>> point_c.initialBearingTo(point_a)
180.00000114300522
```

**Comment by mrJean1** [comment]
The root cause is in method `angleTo`, lines 278-279 of module [vectorBase.py](https://github.com/mrJean1/PyGeodesy/blob/master/pygeodesy/vector3dBase.py):
```
    if s < EPS0:
        return _0_0
```
Both those lines must be removed.  Thank you for reporting the issue!

**Comment by mrJean1** [comment]
[PyGeodesy 21.7.2](https://pypi.org/project/PyGeodesy/21.7.2/) includes the changes to produce the correct result from both methods `sphericalNvector.LatLon.initialBearingTo` and `-.finalBearingTo` plus a regression test.
