### ISSUE TITLE
EcefKarney.forward method error

### ISSUE THREAD

**Issue by terbeest** [mrJean1/PyGeodesy#57]
Hi there,

I am getting an error when I provide two floats in the EcefKarney.forward method shown below. The two floats are labeled as Ytd (longitude) and Xtd (latitude) as decimal WGS84 points. Please advise. Thanks!

Ytd = degrees(asin(sin(Y0r)*cos(d/r)+cos(Y0r)*sin(d/r)*cos(yaw)))
Xtd = degrees(X0r+atan2(sin(yaw)*sin(d/r)*cos(Y0r), cos(d/r)-sin(Y0r)*sin(radians(Ytd))))
ecef1 = EcefKarney.forward(Ytd, Xtd, 0, 0)

Error message:

Traceback (most recent call last):
  File "d:\anaconda\envs\azel\azel\georec.py", line 38, in <module>
    ecef1 = EcefKarney.forward(Ytd, Xtd, 0, 0)
  File "D:\anaconda\envs\azel\lib\site-packages\pygeodesy\ecef.py", line 341, in forward 
    return _EcefBase._forward(self, *llhn, M=M)
  File "D:\anaconda\envs\azel\lib\site-packages\pygeodesy\ecef.py", line 228, in _forward
    E = self.ellipsoid
AttributeError: 'float' object has no attribute 'ellipsoid'

**Comment by mrJean1** [comment]
`EcefKarney` is a _class_ which must be instantiated, _before_ methods as `forward` can be called.  Instead of
```
  ecef1 = EcefKarney.forward(Ytd, Xtd, ...)
```
use
```
  from pygeodesy import Datums, EcefKarney
  ek = EcefKarney(Datums.WGS84)  # or an some other datum, ellipsoid, etc.
...
  ecef1 = ek.forward(Ytd, Xtd, ...)
```
HTH.

**Comment by terbeest** [comment]
it works! thanks very much!

**Comment by mrJean1** [comment]
All ECEF classes in the latest [PyGeodesy 21.9.12](https://pypi.org/project/PyGeodesy/) release have a new method called `forwar_` (trailing underscore replacing `d`) to specify the lat- and longitude in `radians`.   Using that method instead of the `forward` method avoids double conversions of `radians` and `degrees`.
