### ISSUE TITLE
intersection

### ISSUE THREAD

**Issue by sbonaime** [mrJean1/PyGeodesy#58]
Hi,
Is there a way using PyGeodesy to compute the intersection of two lines defined each by  latlon and bearings but for one point, I want to find the intersection point going in Bearing direction and bearing + 180° ?
I know A and bearing_A and C and bearing_C. I want to find G but I don't know if it on the right or left of C.

Thanks

![Capture d’écran 2021-09-10 à 10-09-21 10 12 48](https://user-images.githubusercontent.com/750709/132822704-27af30d6-70e6-45b6-bc2a-8c5bf60fe193.png)

**Comment by mrJean1** [comment]
Use method [sphericalTrigonometry.LatLon.intersection](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.sphericalTrigonometry.LatLon-class.html#intersection) (or [sphericalNvector.LatLon.intersection](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.sphericalNvector.LatLon-class.html#intersection)) to obtain the intersection of the 2 paths, each specified by a start point and a bearing.

Then, use method [compassAngleTo](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.latlonBase.LatLonBase-class.html#compassAngleTo) or [initialBearingTo](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.sphericalTrigonometry.LatLon-class.html#initialBearingTo) to get the `bearing_G` from point C to G.  If `bearing_G` is close** to `bearing_C`, G is to the left of C.  if `bearing_C` and `bearing_G` are about 180 degrees apart, G is to the right of C.

Untested though.
__
**) for example, `abs(bearing_G - bearing_C) < 90 `or some smaller value.

**Comment by mrJean1** [comment]
One comment, one question.

- A forthcoming release of PyGeodesy will support ellipsoidal `intersection3` methods and functions with paths defined by two points _or_ by a start point and an initial bearing.

-  The location of the intersection point to the "left/right" of a start point and bearing is still unclear.  Wouldn't it be preferable to use positive/negative or forward/reverse to indicate that the intersection point is along the bearing past/before the start point?

**Comment by mrJean1** [comment]
[PyGeodesy 21.9.12](https://github.com/mrJean1/PyGeodesy) includes _ellipsoidal_ function `intersection3` and _ellipsoidal_ LatLon methods `intersection3` enhanced to support paths specified by two points or by a start point and an initial bearing, similar to the spherical function and method `intersection`.

The 3-tuple returned by `intersection3` include 2 items `outside1` and `outside2` indicating `where` the intersection point is located on each path.  For paths specified by a start point and an initial bearing, `outside1` and `-2` will be _negative_ if the intersection is located _before_, zero if the intersection and start point coincide or `positive` if the intersection point is _after_ the start point, in the direction of the initial bearing.

**Comment by mrJean1** [comment]
[PyGeodesy 21.9.16](https://pypi.org/project/PyGeodesy/) include modified ellipsoidal and spherical path intersections to return consistent results from paths both specified by a point and bearing.
