### ISSUE TITLE
Do you consider putting docs online?

### ISSUE THREAD

**Issue by hckr** [mrJean1/PyGeodesy#6]
You probably could just change name of `doc.html` to `index.html` and enable GitHub pages from master branch.

**Comment by mrJean1** [comment]
Will do that, soon.  Thank you for the suggestion.

**Comment by mrJean1** [comment]
Changing the doc.html file name is not sufficient.  There is more to serving docs from GitHub.

**Comment by hckr** [comment]
You should also enable GitHub pages on master branch, then the docs should show up here: https://mrjean1.github.io/PyGeodesy

**Comment by mrJean1** [comment]
The docs are at [PyPI](https://pythonhosted.org/PyGeodesy/).  Is that OK?

**Comment by hckr** [comment]
I ended up using another library, but it should be useful for another possible users. Thanks :)

**Comment by mrJean1** [comment]
Closed for now.
