### ISSUE TITLE
Find the shortest distance between a point and line segments (not line)

### ISSUE THREAD

**Issue by sbonaime** [mrJean1/PyGeodesy#60]
Hi,
Is there to find the shortest distance between a point and line segments (not line) like in this image from https://stackoverflow.com/questions/27161533/find-the-shortest-distance-between-a-point-and-line-segments-not-line
![image](https://user-images.githubusercontent.com/750709/134372484-9745589e-399b-4a7e-9011-4e6fe3a79d4d.png)

The algorithm works fine in regular geometry but I am not sure with LatLon...
Thanks

**Comment by sbonaime** [comment]
I find a python solution here
https://www.geeksforgeeks.org/minimum-distance-from-a-point-to-the-line-segment-using-vectors/

**Comment by mrJean1** [comment]
Use LatLon method [nearestOn](https://mrjean1.github.io/PyGeodesy/) the find the closest point.  Then, use the [distanceTo](https://mrjean1.github.io/PyGeodesy/) method  to find the distance.

In addition, there are separate functions called `nearestOn` in the ellipsoidal and spherical modules and there are quite a few distance methods in module [formy](https://mrjean1.github.io/PyGeodesy/), named after the method employed.

**Comment by mrJean1** [comment]
A few more comments.  The mechanism to find the closest point on a line or line segment is different for ellipsoidal and spherical LatLon method `nearestOn`.  

Method `sphericalTrigonometry.LatLon.nearestOn` indirectly calls function [nearestOn5](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.points-module.html#nearestOn5) which uses the [equirectangular](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.formy-module.html#equirectangular_) approximation to _compare_ distances.

Ellipsoidal `nearestOn` methods iterate and convert back and forth between _geodetic_ and _cartesian_ coordinates and use vectorial function `vector3d.nearestOn`** to get the closest point based on the `dot` product (in an _azimuthal equidistant projection_).  For more details, see the references in ellipsoidal method [intersections2](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.ellipsoidalBase.LatLonEllipsoidalBase-class.html#intersections2).

__
**) That function is not `public`, a mistake.  Also, not all ellipsoidal and spherical modules have a function called `nearestOn`, another mistake.
