### ISSUE TITLE
missing g2012b_bin

### ISSUE THREAD

**Issue by SBFRF** [mrJean1/PyGeodesy#64]
1st time user, trying to convert raw ellipsoid values to NAVD88 with g2012b. Have a difficult time interpreting the documentation and couldn't find any examples either on stack or in the documentation, so i'm left here.  if this isn't the forum forgive me.  the initialization for the geoid2012 class requires a bin file for the conversion..... I'm guessing its the actual model, but hard to tell. where does one acquire this bin file?

```
from pygeodesy import geoids 
 instance = geoids.GeoidG2012B()

Traceback (most recent call last):
  File "/home/spike/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-a7fe79c11b99>", line 1, in <module>
    instance = geoids.GeoidG2012B()
TypeError: __init__() missing 1 required positional argument: 'g2012b_bin'
```

**Comment by SBFRF** [comment]
on further investigation, I got it!  `https://geodesy.noaa.gov/GEOID/GEOID12B/GEOID12B_CONUS.shtml`

you all may want to consider updating your documentation with a few examples

**Comment by mrJean1** [comment]
Did you see the documention of module [geoids](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.geoids-module.html)?  If so, do the examples not cover your particular usage?  If so, could you provide one?

**Comment by SBFRF** [comment]
yea I did, i didn't really follow any of those as there isn't a practical example, it's missing import statements among other things. As a new user, something like below would be helpful to see  
```
import pandas as pd
from pygeodesy import geoids

fname = "data/ExampleFile.csv"
geoidFile = "data/g2012bu8.bin"
data = pd.read_csv(fname)
data['ellipsoid'] = data.gga_altitude_m - data.gga_height_geoid_m
instance = geoids.GeoidG2012B(geoidFile)
geoidHeight = instance.height(data.latitude, data.longitude)
data['elevation_NAVD88_m'] = data.ellipsoid + geoidHeight
data.plot.scatter('longitude', 'latitude', c='elevation_NAVD88_m', cmap='ocean')
```


![image](https://user-images.githubusercontent.com/8375832/142505640-9b7892d2-c782-4794-96ff-d1b7e6a3d162.png)
.... i'm not sure how i'm supposed to get you the data file i'm using through github issues

**Comment by SBFRF** [comment]
[ExampleFile.csv](https://github.com/mrJean1/PyGeodesy/files/7566404/ExampleFile.csv)
got it here through a drag and drop

**Comment by mrJean1** [comment]
Thank you.  There are links to geoid model files in the class documentation.  Perhaps, some are broken abd slipped those the tests.

Next time, just post an issue and ask for a usage example of any of the `pygeodesy` classes or functions.

**Comment by SBFRF** [comment]
will do, thanks for developing this!  (and being responsive)

**Comment by mrJean1** [comment]
[PyGeodesy 21.11.21](https://pypi.org/project/PyGeodesy/21.11.21/) has updates to the documentation of the [geoids](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.geoids-module.html) module (and the [heights](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.heights-module.html) one), including a reference to the example above.
