### ISSUE TITLE
Suggestion: geodesic equation

### ISSUE THREAD

**Issue by brunolnetto** [mrJean1/PyGeodesy#69]
I have no idea how to do you perform the calculation for the current library. 

Have you tried to utilize the geodesic equation instead of Vincenty's formulae? You require only to compute the Christoffel symbols and some integration method like those available [here](https://docs.scipy.org/doc/scipy/tutorial/integrate.html).

**Comment by mrJean1** [comment]
Not sure what the question is or how to answer it.  Please show an example of the problem you need to solve.

**Comment by brunolnetto** [comment]
It was an advice to utilize the bvp integration tool to calculate the distance you require: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_bvp.html

**Comment by mrJean1** [comment]
Sorry, I’m unaware familiar with any geodetic or geodesic case applicable to a bvp.

**Comment by mrJean1** [comment]
Before getting further into specifics, what would be the difference/benefit of a bvp-based geodesic approach?

What would bvp offer, something not already provided by the 4 existing ellipsoidal models in PyGeodesy?  Lastly, is there anything available in the other models which bvp can not deliver?

Also, bvp can compute the distance along a geodesic through 2 points.  What about computing the destination at a given distance along a geodesic through a given location?

**Comment by brunolnetto** [comment]
Answer 1: The advantage is a general equation-based computation of geodesic curve.

Answer 2: The additional proposal brings a geometric approach whose approximations regards only to the integration step.

Answer 3: I am not able to evaluate each implemented method. My argument is the geodesic approach is how mathematics handle with distance on surfaces. 

Answer 4: I am glad you ask:  This concept is called [exponential map](https://en.wikipedia.org/wiki/Exponential_map_(Riemannian_geometry)).

The coordinates of given points on a surface S respective to certain coordinate p are those on the curve tail $\gamma(1)$ such that initial values are position p and velocity v, such that vector v belongs to the tangent space of S and its norm is equal to the desired distance.
