### ISSUE TITLE
Parsing Polar MGRS Coordinates

### ISSUE THREAD

**Issue by CF-FHB-X** [mrJean1/PyGeodesy#70]
Hi there!

Not sure if this is just me, but I'm having issues parsing polar MGRS coordinates. I have some automated tests that generate fake coords for testing some of our code. We're using `pygeodesy` for converting the MGRS coords back to lat/lon. I'm running into issues, though, with any polar coordinates. 

For example:

```python
from pygeodesy import mgrs
mgrs.parseMGRS("BFS7751499182")
```
Returns the following error: `pygeodesy.mgrs.MGRSError: strMGRS ('BFS7751499182'): invalid`

According to [Wikipedia](https://en.wikipedia.org/wiki/Military_Grid_Reference_System#/media/File:MGRSgridSouthPole.png), this should be a valid MGRS (albeit using the UPS projection instead of UTM). 

Am I just using the wrong function for these?

**Comment by mrJean1** [comment]
Correct and thank you for reporting the issue.  The MGRS convention for both polar regions is different from the non-polar region between 80ºS and 84ºN, see [Polar regions](https://WikiPedia.org/wiki/Military_Grid_Reference_System#Polar_regions).  A update for function `parseMGRS` is forthcoming.

**Comment by mrJean1** [comment]
`PyGeodesy` version [22.07.21](https://github.com/mrJean1/PyGeodesy) includes several enhancements and other updates to handle the MGRS polar (UPS) regions.

Version 22.07.21 is only on [GitHub](https://github.com/mrJean1/PyGeodesy), not yet on PyPI.  Testing is still ongoing, especially converting from LatLon, Utm and Ups instances to MGRS and more test cases need to be added.

**Comment by mrJean1** [comment]
PyGeodesy release [22.07.22](https://github.com/mrJean1/PyGeodesy) handles MGRS polar (UPS) regions and converts correctly forward and reverse between (ellipsoidal) LatLon, Mgrs, Utm and Ups.

Please confirm and close this issue.

**Comment by CF-FHB-X** [comment]
Hey there! 

Just had a sec to test it out and I can confirm that it's converting polar MGRS refs correctly. 

Thanks!

**Comment by mrJean1** [comment]
PyGeodesy [22.8.2](https://pypi.org/project/PyGeodesy/) has several, additional MGRS changes, especially in the _polar_ regions.  Following is a summary.

New MGRS tests to compare the results with Karney's [GeoConvert](https://GeographicLib.sourceforge.io/C++/doc/GeoConvert.1.html) utility, provided the latter is executable.  See module `mgrs` and env variable `PYGEODESY_GEOCONVERT` for more details.

Fixed 3 MGRS issues in converting from and to `LatLon` at latitude 64, -90 and +90.  Set env variable `PYGEODESY_UPS_POLES` to anything other than `"std"` for the previous behavior.

Modified the `prec` argument of methods `Mgrs.toRepr`, `Mgrs.toStr`, `Osgr.toRepr`, `Osgr.toStr` and function `enstr2` to follow Karney's definition of MGRS [PRECISION](https://GeographicLib.SourceForge.io/C++/doc/GeoConvert.1.html#PRECISION).  The default, `prec=0` produces 5 digit easting and northing strings, positive `prec` values add _decimal_ digits (without decimal point), negative `prec`'s remove least-significant _unit_ digits.
