### ISSUE TITLE
DEPRECATED Ned from pygeodesy.ellipsoidalNvector

### ISSUE THREAD

**Issue by PatrikHudak** [mrJean1/PyGeodesy#72]
Hi,

I have used `Ned` class from `pygeodesy.ellipsoidalNvector`, but as per docs (https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.ellipsoidalNvector.Ned-class.html) this is now _DEPRECATED_. The usage was as follows:

```python
>>> from pygeodesy.ellipsoidalNvector import LatLon, Ned
>>> a = LatLon(49.66618, 3.45063)
>>> delta = Ned(-86126, -78900, 1069)
>>> a.destinationNed(delta)
LatLon(48°53′12.01″N, 002°22′29.0″E, +0.20m)
```

Migrating to new `Ned` class from `pygeodesy.ltpTuples`, the previous behaviour fails:

```python
>>> from pygeodesy.ellipsoidalNvector import LatLon
>>> from pygeodesy.ltpTuples import Ned as N
>>> a = LatLon(49.66618, 3.45063)
>>> delta2 = N(-86126, -78900, 1069)
>>> a.destinationNed(delta2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pygeodesy/ellipsoidalNvector.py", line 241, in destinationNed
    _xinstanceof(Ned, delta=delta)
  File ".../pygeodesy/basics.py", line 709, in _xinstanceof
    raise _TypesError(n, v, *Types)
pygeodesy.errors.TypesError: type(delta) ([N:-86126.0, E:-78900.0, D:1069.0]), not an Ned
```

Is this expected or the `pygeodesy.ltpTuples.Ned` class should be used in different way?

Thanks!

Patrik

**Comment by mrJean1** [comment]
This is a bug in line 241 of `pygeodesy/ellipsoidalNvector.py`.  That line
```
_xinstanceof(Ned, delta=delta)
```
should used `_Ned` instead of `Ned` as follows
```
_xinstanceof(_Ned, delta=delta)
```
The forthcoming release 22.9.22 will include the fix.  Thank you for reporting!

**Comment by mrJean1** [comment]
In addition, method `ellipsodialNvector.deltaTo` will have new keyword argument `Ned=Ned` to select the `Ned` class to return the `delta`, either `pygeodesy.Ned` or `pygeodesy.Ned4Tuple` or the _default, DEPRECATED_ `ellipsodialNvector.Ned` for backward compatibility.

**Comment by mrJean1** [comment]
An alpha/pre-release for `22.9.22` is available as [PyGeodesy 22.9.19](https://pypi.org/project/PyGeodesy/).  The latter includes the changes for both methods `ellipsoidalNvector.LatLon.destinationNed` and `-.deltaTo` among several other things.  

If possible, please confirm that no other issues exist.

**Comment by PatrikHudak** [comment]
It works as excepted!

**Comment by mrJean1** [comment]
Thank you and thank you again for reporting and for including a test case.
