### ISSUE TITLE
scipy has deprecated interp2d

### ISSUE THREAD

**Issue by j-carson** [mrJean1/PyGeodesy#78]
Class GeoidPGM uses scipy interp2d function, which has been deprecated

Use of function https://github.com/mrJean1/PyGeodesy/blob/840f4ed496452e15e8eb2fe02f4a8d044f880c37/pygeodesy/geoids.py#L208C19-L208C19

scipy deprecation transition guide http://scipy.github.io/devdocs/notebooks/interp_transition_guide.html

**Comment by mrJean1** [comment]
`RectBivariateSpline`, one of the recommended replacements for `interp2d` is already included in class `GeoidGPM`, see keyword argument `kind`.

Should support for `interp2d` be removed altogether or replaced with an other recommendation?

**Comment by j-carson** [comment]
Honestly I am new to this package, so I was looking at all the kinds and discovered this one was based on deprecated functionality. It seems that the interp2d option should at least be deprecated in PyGeodesy? What happens when the function is removed from scipy is up to you as the maintainer, I think.

**Comment by j-carson** [comment]
Thank you! That sounds like a very reasonable resolution to me.

**Comment by mrJean1** [comment]
Great.  Thank you again.  Closing the issue.
