### ISSUE TITLE
reintroduced error when running after pyinstaller - see #31

### ISSUE THREAD

**Issue by caver456** [mrJean1/PyGeodesy#79]
Noticed this while running an executable created with pyinstaller on Windows 11:

```
PS C:\Program Files (x86)\RadioLog> .\radiolog.exe
Traceback (most recent call last):
  File "radiolog.py", line 333, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pygeodesy\__init__.py", line 585, in <module>
  File "pygeodesy\__init__.py", line 573, in _all
ImportError: missing attributes[2]: pygeodesy.rhumb.RhumbAux, pygeodesy.rhumb.RhumbLineAux
[23696] Failed to execute script 'radiolog' due to unhandled exception!
PS C:\Program Files (x86)\RadioLog>
```

Determined that the development system had pygeodesy 23.11.11, but without a specific version in my project's requirements.txt, pyinstaller on github actions was grabbing pygodesy 23.12.23.

Maybe the same issue that was fixed in #31 was reintroduced between 23.11.11 and 23.12.23?

For now, I hardcoded pygeodesy==23.11.11 in my project's requirements.txt which allowed the pyinstaller-built executable to run.

Details in my project's repo are [here.](https://github.com/ncssar/radiolog/issues/723)  Thanks

**Comment by mrJean1** [comment]
The root cause is the new `rhumb` module: `rhumb` does not set and import `__all__` when `pygeodesy` is frozen, by `pyinstaller`.  PyGeodesy releases 23.12.02, 23.12.12 and 23.12.23 all exhibit the issue.  The problem is fixed in forthcoming release 23.12.29.

**Comment by caver456** [comment]
Sounds good, thanks for the quick follow-up and for the excellent project.

**Comment by mrJean1** [comment]
Plese double check that the problem has been resolved for your project.  If so, please close this issue.

**Comment by caver456** [comment]
It does work for pygeodesy==23.12.29 in requirements.txt - thanks for the fix.

Do you anticipate that new versions going forward will need a a new fix each time, or, should the fix that just got applied allow all future versions to work (in theory)?  Basically, do you think it's safe to remove the specific pygeodesy version number from requirements.txt?

**Comment by mrJean1** [comment]
This issue will not happen again: a regression test will added to detect it prior to any future release.

**Comment by caver456** [comment]
Thanks!  Closing as fixed!

**Comment by mrJean1** [comment]
FYI, (1) [PyGeodesy 24.1.10](https://pypi.org/project/PyGeodesy/) includes the new regression test `testFrozen.py`.

(2) Module `ellipsoidalBase` and class `LatLonEllipsoidalBase` are both documented as _INTERNAL_.   Better is to use the _public_ class `LatLon` from module `ellipsoidalExact` or `ellipsoidalVincenty` because there are important and subtle differences between the `LatLon` class from the 5 ellipsoidal modules.  Other modules and classes with names ending in _-Base_ are also _INTERNAL_ as if starting with an underscore.
