### ISSUE TITLE
Extend intermediateTo to support any number as a fraction

### ISSUE THREAD

**Issue by naktinis** [mrJean1/PyGeodesy#8]
Currently it only supports range `0..1` but it is not too difficult to extend it to support an arbitrary distance along great circle defined by `self` and `other` including negative values.

**Comment by mrJean1** [comment]
Thank you for suggesting.  An `alongTrackDictanceTo` method was ready before, but without tests.  Lacking that, I'm using the same tests as `crossTrackDistanceTo` and assume the results are correct.  An update is will allow soon.

**Comment by mrJean1** [comment]
See version PyGeodesy-17.04.26, especially the sphericalTrigonometry test results.

**Comment by naktinis** [comment]
Not sure what your opinion is about extending `intermediateTo` (which this issue was about). For some reason we were only discussing `alongTrackDistanceTo`.

**Comment by mrJean1** [comment]
My apologies, I clicked the wrong issue, twice.  The name `intermediateTo` (and `intermediateChordTo`) and the comments in the JS code implied that only `factor` values `0..1` were suitable.  But the JS code puts no restriction on the `factor` value, I'd be happy to do that in the Python version.

**Comment by naktinis** [comment]
Completely agree about naming.

**Comment by mrJean1** [comment]
Good.  There are 3 spherical `intermediate...` methods and the `fraction` restriction is being removed for all, just to be consistent.

**Comment by mrJean1** [comment]
All done in `PyGeodesy-17.4.28`.

**Comment by naktinis** [comment]
Are there any tests for fractions outside 0..1? I think `h` computation does not work for such values. Otherwise it looks ok.

**Comment by mrJean1** [comment]
No tests, but I'll check with the original author.  Also, I'll add a height keyword.  If not None, it will replace the fractional default.

**Comment by mrJean1** [comment]
A keyword argument `height=None` has been added all `intermediate...To` and several other methods to override the computed, default or fractional height value in `PyGeodesy-17.4.30`.  There are other updates.

**Comment by mrJean1** [comment]
@Naktinis, has this been resolved to your satisfaction?

**Comment by naktinis** [comment]
Seems to work as expected. Thank you.
