### ISSUE TITLE
feature request: PyGeodesy citation in academic works

### ISSUE THREAD

**Issue by abubelinha** [mrJean1/PyGeodesy#81]
In case we need to cite this package, which is the suggested way?  

I mean a format "Author (year) Title. Place-were-published" to include in bibliographic references.
Or if you archive the repository in [Zenodo](https://zenodo.org/login/?next=%2Faccount%2Fsettings%2Fgithub%2F) we can just grab citation from there?  I think that would be great:
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Thanks a lot
@abubelinha

**Comment by mrJean1** [comment]
Thank you for the reminder.  I followed your instructions and turned 2 of my GitHub repositories ON.
However, I didn't see bullet (3) _Review the information about access permissions, then click **Authorize zenodo**_.

If this is sufficient, please close this issue.  Otherwise, please advise.

**Comment by abubelinha** [comment]
Actually I don't really know how it works.

I passed you the link since I know other package publishers using this Zenodo system (i.e. @dimus) and it works.

Maybe you didn't publish any new release of your package yet? 
I think Zenodo only archives realeases: I guess that's kind of versioning system.
So it's not enough that your repo is public: you need to "make a release" (whatever it is, lol)

**Comment by abubelinha** [comment]
There is also an alternative: you can define the way you want people should cite your page:

https://github.com/rpy2/rpy2/issues/861#issuecomment-1429329436

 (again, I just read the info but have never done it since I am not author of any packages)

**Comment by mrJean1** [comment]
Sorry.

**Comment by abubelinha** [comment]
> Sorry.

About what?

**Comment by mrJean1** [comment]
Since you can’t help, there’s no point.  Amen.

**Comment by abubelinha** [comment]
There is also an alternative: you can define the way you want people should cite your page:

https://github.com/rpy2/rpy2/issues/861#issuecomment-1429329436

 (again, I just read the info but have never done it since I am not author of any packages)

**Comment by abubelinha** [comment]
What else do you want from me?

This is just something about github configuration and I am not github staff.

I already provided you two alternatives.
You simply need to follow one of them.

If you want your project to be easily cited.
If not, I will cite the js libraries you cite.
Amen

**Comment by mrJean1** [comment]
_Please, **DO NOT CITE** my NOR any other works ON MY BEHALF!_  And stop posting on this topic.
